In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
df=pd.read_csv("Student-Performance-csv_T4qDx.csv")
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [2]:
le = LabelEncoder()
df["Extracurricular Activities"] = le.fit_transform(df["Extracurricular Activities"])
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [3]:
x=df.drop("Performance Index",axis=1)
y=df["Performance Index"]

In [4]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [8]:
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
model = LinearRegression()
model.fit(X_train_scaled,Y_train)
y_preds = model.predict(X_test_scaled)

In [10]:
mean_squared_error(Y_test,y_preds)

4.7007565676357554

In [11]:
r2_score(Y_test,y_preds)

0.9871377556501358

In [12]:
with open("student_lr_final_model.pkl","wb") as file:
    pickle.dump((model,scaler,le),file)